version: "3.9"
services:


  zookeeper:
      image: confluentinc/cp-zookeeper:latest
      ports:
       - 22181:2181
       - 2888:2888
       - 3888:3888
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

  kafka:
      image: confluentinc/cp-kafka:latest
      depends_on:
        - zookeeper
      ports:
        - 9092:9092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_CREATE_TOPICS: "test1:1:1"

  kafka-ui:
      image: provectuslabs/kafka-ui
      container_name: kafka-ui
      ports:
        - "8090:8080"
      restart: always
      environment:
        - KAFKA_CLUSTERS_0_NAME=local
        - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
        - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      links:
       - kafka
       - zookeeper

# -------------------------------------------------------------

  sw1_app:
    build:
      context: SW1
    hostname: SW1_APP
    ports:
      - "8442:8442"
    environment:
      # - DB_URL=postgres1:6432
      # - DB_URL=jdbc:postgresql://postgres1:5432/trsis1
      - DB_URL=jdbc:h2:mem:testdb
      # - DB_USERNAME=postgres
      - DB_USERNAME=sa
      # - DB_PASSWORD=1234
      - DB_PASSWORD=password
      - KAFKA_HOST=kafka:9092
      - KAFKA_GROUP_ID=GROUP1
    links:
      - kafka

  sw2_app:
    build:
      context: SW1
    hostname: SW2_APP
    ports:
      - "8443:8442"
    environment:
      # - DB_URL=postgres1:6432
      # - DB_URL=jdbc:postgresql://postgres2:5433/trsis2
      - DB_URL=jdbc:h2:mem:testdb
      # - DB_USERNAME=postgres
      - DB_USERNAME=sa
      # - DB_PASSWORD=1234
      - DB_PASSWORD=password
      - KAFKA_HOST=kafka:9092
      - KAFKA_GROUP_ID=GROUP2
    links:
      - kafka